<?php
/**
 * Uthando CMS (http://www.shaunfreeman.co.uk/)
 *
 * @author      Shaun Freeman <shaun@shaunfreeman.co.uk>
 * @link        https://github.com/uthando-cms for the canonical source repository
 * @copyright   Copyright (c) 26/08/17 Shaun Freeman. (http://www.shaunfreeman.co.uk)
 * @license     see LICENSE
 */

namespace UthandoBlog\InputFilter;


use Zend\InputFilter\InputFilter;

/**
 * Class Comment
 * @package UthandoBlog\InputFilter
 */
class Comment extends InputFilter
{
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }
}
