<?php $this->headTitle('Tags') ?>
<?php $this->layout()->pageTitle = $this->translate('Tags');?>

<?php $this->placeholder('header-buttons')->captureStart();?>
<a href="<?=$this->url('admin/blog/settings');?>" data-toggle="tooltip" title="<?=$this->translate('Settings');?>" class="btn btn-primary">
    <i class="fa fa-cog"></i>
</a>
<a href="<?=$this->url('admin/blog/tag/edit', [
    'action' => 'add'
]);?>" type="submit" data-toggle="tooltip" title="<?=$this->translate('Add Post');?>" class="btn btn-primary">
    <i class="fa fa-plus"></i>
</a>
<?php $this->placeholder('header-buttons')->captureEnd();?>

<div class="panel panel-default">
    <div class="panel-heading">
        <h3 class="panel-title"><i class="fa fa-list"></i> <?=$this->translate('Tag List');?></h3>
    </div>
    <div class="panel-body">
        <?=$this->partial('uthando-admin/partial/search', [
            'name'			=> 'tag',
            'searchInputs'	=> [
                $this->translate('Tag') => 'name',
            ],
        ]);?>
    </div>
    <div id="table-tag" class="admin-table">
        <?=$this->partial('uthando-blog/tag/list', [
            'models' => $this->models
        ]); ?>
    </div>
</div>

<script>
    $(document).ready(function(){
        $('#table-news').dataGrid({
            url : 'tag/list',
            query: { sort : 'tagId' },
            searchForm : $('#search-tag'),
            paging : 'links',
            columnSort: true
        });
    });
</script>
