<?php if (count($this->models) > 0): ?>
    <div class="table-responsive">
        <table class="table table-hover table-bordered table-condensed">
            <thead>
            <tr>
                <th data-field="postId">Post Id</th>
                <th data-field="title">Title</th>
                <th data-field="userId">Created By</th>
                <th data-field="dateCreated">Date Created</th>
                <th data-field="dateModified">Date Modified</th>
                <th>Actions</th>
            </tr>
            </thead>
            <tbody>
            <?php /* @var $row \UthandoBlog\Model\Post */ ?>
            <?php foreach($this->models as $row): ?>
                <tr>
                    <td><?=$this->escapeHtml($row->getPostId()); ?></td>
                    <td><?=$this->escapeHtml($row->getTitle()); ?></td>
                    <td><?=$this->escapeHtml($row->getUser()->getFullName());?></td>
                    <td><?=$this->escapeHtml($this->formatDate($row->getDateCreated())); ?></td>
                    <td><?=$this->escapeHtml($this->formatDate($row->getDateModified())); ?></td>
                    <td>
                        <?=$this->partial('uthando-admin/partial/edit-actions', [
                            'pk'		=> 'postId',
                            'id'		=> $row->getPostId(),
                            'tableName'	=> 'post',
                            'route'		=> 'admin/blog/post/edit',
                        ]);?>
                    </td>
                </tr>
            <?php endforeach; ?>
            </tbody>
        </table>
    </div>

    <?=$this->paginationControl(
        $this->models,
        'Elastic',
        'application/partial/paginate',
        ['route' => 'admin/blog/post/page']
    ); ?>

<?php else: ?>
    <h4>There are no Posts yet.</h4>
<?php endif; ?>