<?php if (count($this->models) > 0): ?>
    <div class="table-responsive">
        <table class="table table-hover table-bordered table-condensed">
            <thead>
            <tr>
                <th data-field="tagId">Tag Id</th>
                <th data-field="name">Name</th>
                <th data-field="seo">SEO</th>
                <th>Actions</th>
            </tr>
            </thead>
            <tbody>
            <?php /* @var $row \UthandoBlog\Model\Tag */ ?>
            <?php foreach($this->models as $row): ?>
                <tr>
                    <td><?=$this->escapeHtml($row->getTagId()); ?></td>
                    <td><?=$this->escapeHtml($row->getName()); ?></td>
                    <td><?=$this->escapeHtml($row->getSeo());?></td>
                    <td>
                        <?=$this->partial('uthando-admin/partial/edit-actions', [
                            'pk'		=> 'tagId',
                            'id'		=> $row->getTagId(),
                            'tableName'	=> 'post',
                            'route'		=> 'admin/blog/tag/edit',
                        ]);?>
                    </td>
                </tr>
            <?php endforeach; ?>
            </tbody>
        </table>
    </div>

    <?=$this->paginationControl(
        $this->models,
        'Elastic',
        'application/partial/paginate',
        ['route' => 'admin/blog/tag/page']
    ); ?>

<?php else: ?>
    <h4>There are no Tags yet.</h4>
<?php endif; ?>