<?php $this->headTitle('Categories') ?>
<?php $this->layout()->pageTitle = $this->translate('Categories');?>

<?php $this->placeholder('header-buttons')->captureStart();?>
<a href="<?=$this->url('admin/blog/settings');?>" data-toggle="tooltip" title="<?=$this->translate('Settings');?>" class="btn btn-primary">
    <i class="fa fa-cog"></i>
</a>
<a href="<?=$this->url('admin/blog/category/edit', [
    'action' => 'add'
]);?>" type="submit" data-toggle="tooltip" title="<?=$this->translate('Add Post');?>" class="btn btn-primary">
    <i class="fa fa-plus"></i>
</a>
<?php $this->placeholder('header-buttons')->captureEnd();?>

<div class="panel panel-default">
    <div class="panel-heading">
        <h3 class="panel-title"><i class="fa fa-list"></i> <?=$this->translate('Category List');?></h3>
    </div>
    <div class="panel-body">
        <?=$this->partial('uthando-admin/partial/search', [
            'name'			=> 'category',
            'searchInputs'	=> [
                $this->translate('Category') => 'name',
            ],
        ]);?>
    </div>
    <div id="table-category" class="admin-table">
        <?=$this->partial('uthando-blog/category/list', [
            'models' => $this->models
        ]); ?>
    </div>
</div>

<?php $this->placeholder('js-scripts')->captureStart();?>
<script>
    $(document).ready(function(){
        $('#table-category').dataGrid({
            url : 'category/list',
            query: { sort : 'lft' },
            searchForm : $('#search-category'),
            paging : 'links',
            columnSort: true
        });
    });
</script>
<?php $this->placeholder('js-scripts')->captureEnd();?>
